DEFINES *= QT_DISABLE_DEPRECATED_BEFORE=0x060000
DEFINES *= QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
DEFINES *= QT_DEPRECATED_WARNINGS


contains(DEFINES, MPI3_BUILD_DESKTOP):CONFIG += c++1z


BUILD_TARGET = mpi3$${BUILD_TARGET}
win32:BUILD_VERSION = $${BUILD_VERSION}.0
TARGET = $$BUILD_TARGET
VERSION = $$BUILD_VERSION


message("BUILD: $$TEMPLATE $$TARGET v$$VERSION")
